spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://delivva-notification-service.cq4rmadfc3cu.eu-north-1.rds.amazonaws.com:5432/notification_db
    username: delivva
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  rabbitmq:
    username: Delivva
    password: delivvadevelopers4
    addresses: amqps://b-24e330b5-34c3-48c1-87df-d65aefcd7ec3.mq.us-east-1.amazonaws.com:5671
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 1

  mail:
    host: smtp.gmail.com
    port: 587
    username: delivvavention@gmail.com
    password: uyudrczhdvvkulsb
    properties:
      mjaail:
        smtp:
          auth: true
      mail:
        smtp:
          starttls:
            enable: true

rabbitmq:
  queue:
    authorization-service: authorization_service_queue
    dispute-service: dispute_service_queue
    core-service: core_service_queue

cloud:
  auth-service:
    url: http://Delivva-testing-environment-env.eba-jighrhr6.us-east-1.elasticbeanstalk.com

jwt:
  secret-key: 753778214125442A472IkphdZSIsImasV4cCIee6MTY4sdNzUwMTQwN3F452848567890iuyiu67567886578uyutuio78654678976549eyJS678965467uior678545
