spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_service_db
    username: postgres
    password: adminroot
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
#  rabbitmq:
#    username: Delivva
#    password: delivvadevelopers4
#    addresses: amqps://b-24e330b5-34c3-48c1-87df-d65aefcd7ec3.mq.us-east-1.amazonaws.com:5671

  mail:
    host: smtp.gmail.com
    port: 587
    username: delivvavention@gmail.com
    password: uyudrczhdvvkulsb
    properties:
      mjaail:
        smtp:
          auth: true
      mail:
        smtp:
          starttls:
            enable: true
  jpa:
    show-sql: true

rabbitmq:
  queue:
    authorization-service: authorization_service_queue
    dispute-service: dispute_service_queue
