name: CI-CD for notification service

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: target/authorization_service-0.0.1-SNAPSHOT.jar

#  deploy:
#    needs: build
#    name: deploy
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download JAR
#        uses: actions/download-artifact@v2
#        with:
#          name: artifact
#
#      - name: Deploy project to AWS
#        uses: einaregilsson/beanstalk-deploy@v20
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
#          application_name: delivva-testing-environment
#          version_label: ${{ github.SHA }}
#          region: eu-north-1
#          deployment_package: Notification_Service-0.0.1-SNAPSHOT.jar
